import Nav from "./components/Nav"
import Footer from './components/Footer'
import type { Metadata } from "next";
import localFont from "next/font/local"
import 'app/sass/globals.sass'

const fraunces = localFont({
  src: "./fonts/Fraunces-VariableFont_wght.ttf",
  variable: "--font-fraunces"
});

const manrope = localFont({
  src: "./fonts/Manrope-VariableFont_wght.ttf",
  variable: "--font-manrope"
});

export const metadata: Metadata = {
  title: "Workit Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fraunces.variable} ${manrope.variable}`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
